name: Remind PR author to delete branch

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  
jobs:
  comment-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on merged PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: `@${context.payload.pull_request.user.login} This PR has been merged. Please remember to delete the branch if it's no longer needed.`
            })
